namespace Api.Constants
{
    public static class ValidationErrors
    {
        public const string CREATE_USER_EMAIL_NOT_VALID = "CREATE_USER_EMAIL_NOT_VALID";
        public const string CREATE_USER_PASSWORD_LENGTH = "CREATE_USER_PASSWORD_LENGTH";
        public const string CREATE_USER_PASSWORD_MUST_CONTAIN_UPPERCASE = "CREATE_USER_PASSWORD_MUST_CONTAIN_UPPERCASE";
        public const string CREATE_USER_PASSWORD_MUST_CONTAIN_NUMBER = "CREATE_USER_PASSWORD_MUST_CONTAIN_NUMBER";
        public const string CREATE_USER_PASSWORD_MUST_CONTAIN_SYMBOL = "CREATE_USER_PASSWORD_MUST_CONTAIN_SYMBOL";
        public const string CREATE_USER_PASSWORD_NOT_VALID = "CREATE_USER_PASSWORD_NOT_VALID";
        public const string LOGIN_EMAIL_NOT_VALID = "LOGIN_EMAIL_NOT_VALID";
        public const string LOGIN_MUST_PROVIDE_PASSWORD = "LOGIN_MUST_PROVIDE_PASSWORD";
    }
}
